--liquibase formatted sql

--changeset dorixid:init_database
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.commentraitings
(
    is_like boolean NOT NULL,
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT commentraitings_pkey PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    date_time timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    idea_id bigint NOT NULL,
    user_id bigint NOT NULL,
    text character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.credentials
(
    active boolean NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password_id bigint NOT NULL,
    user_id bigint,
    e_mail character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT credentials_pkey PRIMARY KEY (id),
    CONSTRAINT credentials_password_id_key UNIQUE (password_id),
    CONSTRAINT credentials_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.databasechangelog
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) COLLATE pg_catalog."default" NOT NULL,
    md5sum character varying(35) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    comments character varying(255) COLLATE pg_catalog."default",
    tag character varying(255) COLLATE pg_catalog."default",
    liquibase character varying(20) COLLATE pg_catalog."default",
    contexts character varying(255) COLLATE pg_catalog."default",
    labels character varying(255) COLLATE pg_catalog."default",
    deployment_id character varying(10) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.databasechangeloglock
(
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.files
(
    comment_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    idea_id bigint,
    message_id bigint,
    uploader_id bigint NOT NULL,
    bucket character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT files_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ideas
(
    date_time timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint NOT NULL,
    user_id bigint,
    description character varying(1600) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ideas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    reciver_user_id bigint NOT NULL,
    sender_user_id bigint NOT NULL,
    text character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.moderators
(
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT moderators_pkey PRIMARY KEY (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.passwords
(
    date_of_change timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT passwords_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pointestimates
(
    point_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT pointestimates_pkey PRIMARY KEY (point_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    active boolean,
    avatar bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT projects_avatar_key UNIQUE (avatar),
    CONSTRAINT projects_title_key UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS public.surveys
(
    end_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    description character varying(300) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT surveys_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    avatar_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nickname character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_avatar_id_key UNIQUE (avatar_id),
    CONSTRAINT users_nickname_key UNIQUE (nickname)
);

CREATE TABLE IF NOT EXISTS public.votingestimates
(
    is_like boolean NOT NULL,
    idea_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT votingestimates_pkey PRIMARY KEY (idea_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.votingpoints
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    survey_id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT votingpoints_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.commentraitings
    ADD CONSTRAINT fkf5alqd8wvogcouu0atpe9psyj FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.commentraitings
    ADD CONSTRAINT fkt0np5j07ebuj9mixbxxviipvf FOREIGN KEY (comment_id)
        REFERENCES public.comments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fke0g88a07p93xa608dt5ea3pw FOREIGN KEY (idea_id)
        REFERENCES public.ideas (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.credentials
    ADD CONSTRAINT fk3avbhdmdw7t190y0pfluno8gq FOREIGN KEY (password_id)
        REFERENCES public.passwords (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS credentials_password_id_key
    ON public.credentials(password_id);


ALTER TABLE IF EXISTS public.credentials
    ADD CONSTRAINT fkcbcgksvnqvqxrrc4dwv3qys65 FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS credentials_user_id_key
    ON public.credentials(user_id);


ALTER TABLE IF EXISTS public.files
    ADD CONSTRAINT fk3cfjbplxrqcb1n7qi9dsgckom FOREIGN KEY (comment_id)
        REFERENCES public.comments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.files
    ADD CONSTRAINT fk6pp46ifm73sdejnw0n7co96b3 FOREIGN KEY (message_id)
        REFERENCES public.messages (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.files
    ADD CONSTRAINT fk6wyrnirk5xwq8ilgtjof1b09a FOREIGN KEY (idea_id)
        REFERENCES public.ideas (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.files
    ADD CONSTRAINT fkhaj8rngy0ky91ndcqv2isi9cr FOREIGN KEY (uploader_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ideas
    ADD CONSTRAINT fkcifipqiu010cssb7rbunpqlls FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ideas
    ADD CONSTRAINT fkt4qp1368gdn4wk6ih62bj80ym FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fkk4mihn10ohqge2as0b7nqlskw FOREIGN KEY (reciver_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fkk4mpqp6gfuaelpcamqv01brkr FOREIGN KEY (sender_user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.moderators
    ADD CONSTRAINT fk88trnuotm3t0s0ew7cnpkup4a FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.moderators
    ADD CONSTRAINT fkmodqwh8otm3uvi7j6wb9igo2r FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pointestimates
    ADD CONSTRAINT fk9p7mqt95ptqfbtfmbfgreq67h FOREIGN KEY (point_id)
        REFERENCES public.votingpoints (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pointestimates
    ADD CONSTRAINT fkb3j9dwev1jglb85r55nnnsaxn FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk78w8yx6dt2r444ilsu37jpwj7 FOREIGN KEY (avatar)
        REFERENCES public.files (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS projects_avatar_key
    ON public.projects(avatar);


ALTER TABLE IF EXISTS public.surveys
    ADD CONSTRAINT fkegppux55yreqnrvbv6ybrn7k7 FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.surveys
    ADD CONSTRAINT fkiydpdbdg90l5bl365gt67qgrn FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fkda0fl66rh9qsoty4s66xk29m6 FOREIGN KEY (avatar_id)
        REFERENCES public.files (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS users_avatar_id_key
    ON public.users(avatar_id);


ALTER TABLE IF EXISTS public.votingestimates
    ADD CONSTRAINT fk98kbb0nt48lpav489kp13oa6q FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.votingestimates
    ADD CONSTRAINT fkd25wx5of5lg4e6apspgtm8tsn FOREIGN KEY (idea_id)
        REFERENCES public.ideas (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.votingpoints
    ADD CONSTRAINT fk3jyw3nqtkp83uqixk0hr6r8xr FOREIGN KEY (survey_id)
        REFERENCES public.surveys (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;