spring.application.name=Voatix

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/Voatix
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#JWT
jwt.expiration=1800000
token.signing.key=secret123456789secret123456789secret123456789