spring.application.name=Voatix

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/Voatix
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

#Liquebase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.level.org.liquibase=DEBUG

#Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


#Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#JWT
jwt.expiration=36000
jwt.public.key=classpath:keys/public.pem
jwt.private.key=classpath:keys/keypair.pem

#Minio
#minio.endpoint = http://minio:9000
#minio.access-key = minioadmin
#minio.secret-key = minioadmin


logging.level.org.springframework.web=DEBUG